version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_cache
    command: ["redis-server", "--maxmemory", "50mb", "--maxmemory-policy", "allkeys-lfu"]
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 100M 

  response-generator:
    build: ./response-generator
    container_name: response_generator
    depends_on:
      - redis
    volumes:
      - ./data:/data # Asegúrate de tener tu CSV en la carpeta local ./data

  traffic-generator:
    build: ./traffic-generator
    container_name: traffic_generator
    depends_on:
      - redis

  metrics:
    build: ./metrics
    container_name: metrics_monitor
    depends_on:
      - redis
